### ISSUE TITLE
Update Sass color() function to not require quotes anymore

### ISSUE THREAD

**Issue by branneman** [branneman/frntndr#4]
#### scss/common/_colors.scss:

``` scss
//
// Colors
//
//  See also: utils/_color.scss
//
//  Usage:
//   border: 1px solid color(primary-a);
//
$colors:
    primary-a     #ff1400,
    primary-b     #bbd62f,
    accent-light  #a0a2a0,
    accent-dark   #727272,
    type          #777,
    type-dark     #444,
    line-light    #f2f2f2,
    line-medium   #d7d7d7,
    line-dark     #b0b0b0
;
```
#### scss/utils/_colors.scss:

``` scss
//
// Function to get a color by it's name
//
//  See also: common/_colors.scss
//
//  Usage:
//   border: 1px solid color(primary-a);
//
@function color($name) {
    $index: null;

    @for $i from 1 through length($colors) {
        @if nth(nth($colors, $i), 1) == $name {
            $index: $i;
        }
    }

    @return nth(nth($colors, $index), 2);
}
```
