### ISSUE TITLE
Sass: make respond-max() mixin use $width - 1px

### ISSUE THREAD

**Issue by branneman** [branneman/frntndr#8]
Example implementation:

``` scss
@mixin respond-max($width) {
    $width: $width - 0.0625; // -1px
    @if $fix-mqs {
        @if $fix-mqs <= $width {
            @content;
        }
    } @else {
        @media screen and (max-width: $width) {
            @content;
        }
    }
}
```

However; this hardcodes 1em = 16px, which is not true for all environments.
